export const LOAD_NOTES_SUCCESS = "LOAD_NOTES_SUCCESS";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const EDITING_NOTE_SUCCESS = "EDITING_NOTE_SUCCESS";
export const REPOSITIONED_NOTE_SUCCESS = "REPOSITIONED_NOTE_SUCCESS";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";

export const LOAD_NOTES_FAILURE = "LOAD_NOTES_FAILURE";
